language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
addons:
  apt:
    packages:
    - pandoc
install:
  - pip install pytest-cov coveralls
  - pip install -e .
script:
  - py.test --cov-config .coveragerc --cov=s3logparse
after_success:
  - coverage combine
  - coveralls
